[Scia Reto](https://sciareto.org) mind map
> __version__=`1.1`,showJumps=`true`
---

# APP

## ChatView
> borderColor=`#00FF00`,collapsed=`true`,fillColor=`#0092FF`

- FILE
<pre>src/components/chatView.vue</pre>

### chatView:message\-block

### chatView:btnBase

## message\-block
> borderColor=`#00FF00`,fillColor=`#0092FF`


### message\-block:avatar

### message\-block:user\-name

### message

## UI
> leftSide=`true`


### button
> borderColor=`#00FF00`,fillColor=`#00FFFF`

- FILE
<pre>src/components/UI/btnBase.vue</pre>

### modal
> fillColor=`#00FFFF`


### avatar
> fillColor=`#00FFFF`


### button\-burger
> borderColor=`#00FF00`,fillColor=`#00FFFF`

- FILE
<pre>src/components/UI/btnBurger.vue</pre>

## accaunt
> borderColor=`#00FF00`,collapsed=`true`,fillColor=`#0092FF`


### settings
> collapsed=`true`,topicLinkUID=`188E8657972A`


#### setting:avatar

#### setting:language

#### setting:color

## menu
> borderColor=`#00FF00`,collapsed=`true`,fillColor=`#0092FF`

- TOPIC
<pre>188E8657972A</pre>

### rooms
